嘗試將array轉圖檔並依序下載

In [7]:
import pickle

In [13]:
with open('2train_test_data.pickle','rb')as file:
    a_dict1=pickle.load(file)
print(a_dict1)

{'inputa': array([[   0,    0,    0, ...,  121,   32,   46],
       [  71,   97,  103, ...,   47,   49,   51],
       [  32,   32,   32, ..., 8240, 1028, 1169],
       ...,
       [ 119,  105,  110, ...,  101,  110,  115],
       [ 116,   98,   97, ...,  116,   76,  103],
       [   0,    0,   66, ...,  100,  105,  111]]), 'inputb': array([[48, 48, 70, 70, 48, 48],
       [70, 70, 70, 70, 70, 70],
       [67, 48, 68, 69, 69, 68],
       ...,
       [70, 70, 70, 70, 70, 70],
       [54, 57, 54, 57, 54, 57],
       [67, 48, 68, 69, 69, 68]]), 'inputc': array([[[[253, 163, 131],
         [255, 176, 124],
         [255, 180, 122],
         ...,
         [245, 243, 253],
         [240, 237, 251],
         [238, 232, 246]],

        [[254, 162, 131],
         [255, 171, 127],
         [255, 178, 122],
         ...,
         [239, 234, 247],
         [236, 232, 247],
         [232, 227, 237]],

        [[254, 162, 130],
         [255, 171, 128],
         [254, 184, 120],
         ...,
       

In [17]:
a_dict1['inputb']

array([[48, 48, 70, 70, 48, 48],
       [70, 70, 70, 70, 70, 70],
       [67, 48, 68, 69, 69, 68],
       ...,
       [70, 70, 70, 70, 70, 70],
       [54, 57, 54, 57, 54, 57],
       [67, 48, 68, 69, 69, 68]])

In [20]:
a_dict1['inputa']

array([[   0,    0,    0, ...,  121,   32,   46],
       [  71,   97,  103, ...,   47,   49,   51],
       [  32,   32,   32, ..., 8240, 1028, 1169],
       ...,
       [ 119,  105,  110, ...,  101,  110,  115],
       [ 116,   98,   97, ...,  116,   76,  103],
       [   0,    0,   66, ...,  100,  105,  111]])

In [21]:
a_dict1['inputc']

array([[[[253, 163, 131],
         [255, 176, 124],
         [255, 180, 122],
         ...,
         [245, 243, 253],
         [240, 237, 251],
         [238, 232, 246]],

        [[254, 162, 131],
         [255, 171, 127],
         [255, 178, 122],
         ...,
         [239, 234, 247],
         [236, 232, 247],
         [232, 227, 237]],

        [[254, 162, 130],
         [255, 171, 128],
         [254, 184, 120],
         ...,
         [234, 226, 234],
         [232, 221, 229],
         [224, 213, 217]],

        ...,

        [[254, 159, 128],
         [252, 194, 172],
         [252, 241, 228],
         ...,
         [173,  75,  79],
         [194,  73,  92],
         [220,  77, 107]],

        [[254, 153, 134],
         [253, 161, 133],
         [247, 160, 164],
         ...,
         [178,  67,  76],
         [206,  68,  97],
         [230,  77, 117]],

        [[252, 119, 138],
         [250, 115, 131],
         [247, 102, 128],
         ...,
         [169,  49,  71],
        

In [22]:
from PIL import Image

In [23]:
import numpy as np

In [87]:
img=np.array(a_dict1['inputc'])

In [40]:
from PIL import Image

In [86]:
print(img)

[[[[253 163 131]
   [255 176 124]
   [255 180 122]
   ...
   [245 243 253]
   [240 237 251]
   [238 232 246]]

  [[254 162 131]
   [255 171 127]
   [255 178 122]
   ...
   [239 234 247]
   [236 232 247]
   [232 227 237]]

  [[254 162 130]
   [255 171 128]
   [254 184 120]
   ...
   [234 226 234]
   [232 221 229]
   [224 213 217]]

  ...

  [[254 159 128]
   [252 194 172]
   [252 241 228]
   ...
   [173  75  79]
   [194  73  92]
   [220  77 107]]

  [[254 153 134]
   [253 161 133]
   [247 160 164]
   ...
   [178  67  76]
   [206  68  97]
   [230  77 117]]

  [[252 119 138]
   [250 115 131]
   [247 102 128]
   ...
   [169  49  71]
   [202  59  96]
   [242  88 126]]]


 [[[253 163 131]
   [255 176 124]
   [255 180 122]
   ...
   [245 243 253]
   [240 237 251]
   [238 232 246]]

  [[254 162 131]
   [255 171 127]
   [255 178 122]
   ...
   [239 234 247]
   [236 232 247]
   [232 227 237]]

  [[254 162 130]
   [255 171 128]
   [254 184 120]
   ...
   [234 226 234]
   [232 221 229]
   [224 213

In [98]:
a_dict1['inputc'].shape

(8955, 48, 48, 3)

In [100]:
a_dict1['inputc'][0].shape

(48, 48, 3)

In [108]:
for i in range (10):
    im=Image.fromarray(a_dict1['inputc'][i])
    
    im.save('test%d.png'%i)
    
